### ISSUE TITLE
not working for me :/

### ISSUE THREAD

**Issue by activeh2** [Triniayo/steam-hourboost-webpanel#1]
Tried installing it on ubuntu 16.04 and isnt working.. missing dependencies (proto..) etc.

**Comment by activeh2** [comment]
now some detailed informations i found out.. 

The SQL File, didnt created the right database, the correct table should be named "accounts" and the database itself "hourboost".

After that when i try to start  - nothing happens (php5 is installed and chmod 777 on start and stop)

i cant figure out more..

**Comment by Triniayo** [comment]
Sorry for the late answer.

Updated it, try again please.

**Comment by Triniayo** [comment]
Problem has been solved.
